JOBS=${JOBS:-4}
EditionId=500原生缩放
Directory=!战·黑体-$EditionId
Archive=战·黑体-$EditionId
AddOnName="战·黑体（500 原生缩放）"

rm -r build/ out/

mkdir -p build/
mkdir -p out/$Directory/

cp src/addon/addon.toc out/$Directory/$Directory.toc
sed -i "s/__REPLACE_IN_BUILD__ADDON_NAME__/$AddOnName/" out/$Directory/$Directory.toc
cp src/addon/Core.lua out/$Directory/Core.lua
sed -i "s/__REPLACE_IN_BUILD__DIRECTORY__/$Directory/" out/$Directory/Core.lua
cp src/addon/FixedSize.xml out/$Directory/FixedSize.xml
sed -i "s/__REPLACE_IN_BUILD__DIRECTORY__/$Directory/;s/__REPLACE_IN_BUILD__EDITION_ID__/$EditionId/" out/$Directory/FixedSize.xml
cp src/addon/LibStub.lua out/$Directory/LibStub.lua
cp src/addon/SharedMedia.lua out/$Directory/SharedMedia.lua

cp src/font/text.otf out/$Directory/text.otf
cp src/font/chat.otf out/$Directory/chat.otf

# generated by `src/xml/xmlparser.py`
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 3 2 && cp build/text-s3,2.otf out/$Directory/text-s3,2.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 5 4 && cp build/text-s5,4.otf out/$Directory/text-s5,4.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 6 5 && cp build/text-s6,5.otf out/$Directory/text-s6,5.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 8 7 && cp build/text-s8,7.otf out/$Directory/text-s8,7.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 13 10 && cp build/text-s13,10.otf out/$Directory/text-s13,10.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 13 11 && cp build/text-s13,11.otf out/$Directory/text-s13,11.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 13 12 && cp build/text-s13,12.otf out/$Directory/text-s13,12.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 14 11 && cp build/text-s14,11.otf out/$Directory/text-s14,11.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 14 13 && cp build/text-s14,13.otf out/$Directory/text-s14,13.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 15 13 && cp build/text-s15,13.otf out/$Directory/text-s15,13.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 16 9 && cp build/text-s16,9.otf out/$Directory/text-s16,9.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 17 14 && cp build/text-s17,14.otf out/$Directory/text-s17,14.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 17 16 && cp build/text-s17,16.otf out/$Directory/text-s17,16.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 19 16 && cp build/text-s19,16.otf out/$Directory/text-s19,16.otf &
((i=i%JOBS)); ((i++==0)) && wait ; python mkscale.py text 19 18 && cp build/text-s19,18.otf out/$Directory/text-s19,18.otf &

wait
cd out/
7z a -t7z -m0=LZMA:d=512m:fb=273 -ms $Archive.7z $Directory/
